"""Tabular I/O is load-bearing: a 10k-row array stage must survive being killed,
and a reader that chokes on a '#' header silently loses every row after it."""
import os

import pytest

from tada_redesign import io as tio

COLUMNS = ("design_id", "parent", "score")


def test_append_row_creates_the_header_then_appends(tmp_path):
    path = str(tmp_path / "out.tsv")
    tio.append_row(path, {"design_id": "d1", "parent": "TadA8e", "score": "1.5"}, COLUMNS)
    tio.append_row(path, {"design_id": "d2", "parent": "TadA9", "score": "2.5"}, COLUMNS)
    lines = open(path).read().splitlines()
    assert lines[0] == "design_id\tparent\tscore"
    assert len(lines) == 3
    rows = tio.read_tsv(path)
    assert [r["design_id"] for r in rows] == ["d1", "d2"]


def test_read_tsv_skips_comment_and_blank_lines(tmp_path):
    path = tmp_path / "c.tsv"
    path.write_text("# generated by something\n\ndesign_id\tparent\tscore\n"
                    "# a mid-file note\nd1\tTadA8e\t1.5\n")
    rows = tio.read_tsv(str(path))
    assert len(rows) == 1
    assert rows[0]["parent"] == "TadA8e"


def test_read_tsv_strips_carriage_returns(tmp_path):
    path = tmp_path / "crlf.tsv"
    path.write_bytes(b"design_id\tparent\tscore\r\nd1\tTadA8e\t1.5\r\n")
    rows = tio.read_tsv(str(path))
    assert rows[0]["score"] == "1.5"


def test_read_tsv_returns_empty_for_a_missing_file(tmp_path):
    assert tio.read_tsv(str(tmp_path / "nope.tsv")) == []


def test_count_rows_is_zero_for_missing_and_header_only(tmp_path):
    assert tio.count_rows(str(tmp_path / "nope.tsv")) == 0
    p = tmp_path / "hdr.tsv"
    p.write_text("design_id\tparent\tscore\n")
    assert tio.count_rows(str(p)) == 0


def test_append_row_rejects_an_unknown_column(tmp_path):
    """A typo'd key must fail loudly rather than being dropped from the row."""
    path = str(tmp_path / "out.tsv")
    with pytest.raises(ValueError):
        tio.append_row(path, {"design_id": "d1", "typo": "x"}, COLUMNS)


def test_append_row_fills_missing_columns_with_NA(tmp_path):
    path = str(tmp_path / "out.tsv")
    tio.append_row(path, {"design_id": "d1"}, COLUMNS)
    assert tio.read_tsv(path)[0]["score"] == "NA"


def test_write_tsv_emits_the_header_comment_first(tmp_path):
    path = str(tmp_path / "w.tsv")
    tio.write_tsv(path, [{"design_id": "d1", "parent": "p", "score": "1"}],
                  COLUMNS, header_comment="dropped 3 rows")
    text = open(path).read()
    assert text.startswith("# dropped 3 rows\n")
    assert tio.read_tsv(path)[0]["design_id"] == "d1"
